// Build-time only: ship preprojected Natural Earth data, not d3/topojson at runtime.
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';
import { geoEqualEarth, geoStream, geoArea, geoCentroid } from 'd3-geo';
import { COUNTRIES } from '../src/data/countries.js';
const numeric = '840 124 484 320 591 192 170 862 604 068 076 032 152 826 372 250 724 380 276 616 804 752 578 246 300 643 504 012 434 818 729 231 404 834 180 566 466 024 710 450 792 682 364 398 586 356 050 156 496 410 392 104 764 704 458 360 608 036 554 598 242 352 304'.split(' ');
if (numeric.length !== COUNTRIES.length) throw new Error('Country mapping mismatch');
const ids = Object.fromEntries(numeric.map((n,i)=>[n,COUNTRIES[i].id]));
const topo = JSON.parse(readFileSync(new URL('../node_modules/world-atlas/countries-110m.json',import.meta.url)));
const projection = geoEqualEarth().fitExtent([[1,1],[99,51]], {type:'Sphere'}).precision(0.025);
const round = p => p.map(n=>+n.toFixed(4));
const projectRings = obj => {
  const rings=[]; let ring;
  geoStream(obj,projection.stream({polygonStart(){},polygonEnd(){},lineStart(){rings.push(ring=[])},lineEnd(){},point(x,y){ring.push(round([x,y]))}}));
  return rings;
};
const countries = feature(topo,topo.objects.countries).features.map(f=>{
  const polygons = f.geometry.type === 'MultiPolygon' ? f.geometry.coordinates : [f.geometry.coordinates];
  const mainland = polygons.map(coordinates=>({type:'Polygon',coordinates})).sort((a,b)=>geoArea(b)-geoArea(a))[0];
  return {id:ids[f.id] || null, name:f.properties.name, rings:projectRings(f), anchor:round(projection(geoCentroid(mainland)))};
});
for(const c of COUNTRIES) if(!countries.some(f=>f.id===c.id)) throw new Error(`Missing ${c.id}`);
writeFileSync(new URL('../src/data/earth.js',import.meta.url), '// Generated by tools/build-earth.mjs. Natural Earth 1:110m, public domain. Equal Earth projection.\nexport const EARTH = '+JSON.stringify({countries,sphere:projectRings({type:'Sphere'})})+';\n');
console.log(`Built ${countries.length} geographic features`);
